insert into genre values (default, 'Rock');
insert into genre values (default, 'Pop');
insert into genre values (default, 'Rap');
insert into genre values (default, 'Country');
insert into genre values (default, 'Electronic');
insert into genre values (default, 'Punk');
insert into genre values (default, 'Folk');
insert into genre values (default, 'Funk');

insert into artist values (default, 'The Beatles');
insert into songwriter values (default, 'John Lennon');
insert into songwriter values (default, 'Paul McCartney');
insert into album values (default, 'A Hard Day_s Night', 1964);
insert into artist_album values (1, 1, TRUE);
insert into song values (default, 'If I Fell');
insert into song_songwriter values (1, 1);
insert into song_songwriter values (1, 2);
insert into track values (default, 'If I Fell', 139, 1, 1);
insert into track_genre values (1, 1);
insert into track_genre values (1, 2);
insert into song values (default, 'Any Time At All');
insert into song_songwriter values (2, 1);
insert into song_songwriter values (2, 2);
insert into track values (default, 'Any Time At All', 131, 1, 2);
insert into track_genre values (2, 1);
insert into track_genre values (2, 2);
insert into song values (default, 'I_ll Be Back');
insert into song_songwriter values (3, 1);
insert into song_songwriter values (3, 2);
insert into track values (default, 'I_ll Be Back', 144, 1, 3);
insert into track_genre values (3, 1);
insert into track_genre values (3, 2);

insert into artist values (default, 'The Rolling Stones');
insert into songwriter values (default, 'Mick Jagger');
insert into album values (default, 'Exile On Main Street', 1972);
insert into artist_album values (2, 2, TRUE);
insert into song values (default, 'Rocks Off');
insert into song_songwriter values (4, 3);
insert into track values (default, 'Rocks Off', 272, 2, 4);
insert into track_genre values (4, 1);
insert into song values (default, 'Rip This Joint');
insert into song_songwriter values (5, 3);
insert into track values (default, 'Rip This Joint', 143, 2, 5);
insert into track_genre values (5, 1);
insert into song values (default, 'Shake Your Hips');
insert into song_songwriter values (6, 3);
insert into track values (default, 'Shake Your Hips', 179, 2, 6);
insert into track_genre values (6, 1);

insert into album values (default, 'Dirty Work', 1986);
insert into artist_album values (2, 3, TRUE);
insert into song values (default, 'Fight');
insert into song_songwriter values (7, 3);
insert into track values (default, 'Fight', 189, 3, 7);
insert into track_genre values (7, 1);
insert into song values (default, 'Hold Back');
insert into song_songwriter values (8, 3);
insert into track values (default, 'Hold Back', 233, 3, 8);
insert into track_genre values (8, 1);
insert into song values (default, 'Dirty Work');
insert into song_songwriter values (9, 3);
insert into track values (default, 'Dirty Work', 233, 3, 9);
insert into track_genre values (9, 1);

insert into artist values (default, 'Carpenters');
insert into songwriter values (default, 'Karen Carpenter');
insert into album values (default, 'Passage', 1977);
insert into artist_album values (3, 4, TRUE);
insert into song values (default, 'Two Sides');
insert into song_songwriter values (10, 4);
insert into track values (default, 'Two Sides', 208, 4, 10);
insert into track_genre values (10, 2);
insert into song values (default, 'Sweet, Sweet Smile');
insert into song_songwriter values (11, 4);
insert into track values (default, 'Sweet, Sweet Smile', 182, 4, 11);
insert into track_genre values (11, 2);
insert into song values (default, 'Bwana She No Home');
insert into song_songwriter values (12, 4);
insert into track values (default, 'Bwana She No Home', 336, 4, 12);
insert into track_genre values (12, 2);

insert into artist values (default, 'Prince');
insert into songwriter values (default, 'Prince');
insert into album values (default, 'ART OFFICIAL AGE', 2014);
insert into artist_album values (4, 5, TRUE);
insert into song values (default, 'CLOUDS');
insert into song_songwriter values (13, 5);
insert into track values (default, 'CLOUDS', 274, 5, 13);
insert into track_genre values (13, 1);
insert into track_genre values (13, 2);
insert into track_genre values (13, 8);
insert into song values (default, 'BREAKDOWN');
insert into song_songwriter values (14, 5);
insert into track values (default, 'BREAKDOWN', 244, 5, 14);
insert into track_genre values (14, 1);
insert into track_genre values (14, 2);
insert into track_genre values (14, 8);
insert into song values (default, 'U KNOW');
insert into song_songwriter values (15, 5);
insert into track values (default, 'U KNOW', 237, 5, 15);
insert into track_genre values (15, 1);
insert into track_genre values (15, 2);
insert into track_genre values (15, 8);

insert into album values (default, 'Purple Rain', 1984);
insert into artist_album values (4, 6, TRUE);
insert into song values (default, 'Let_s Go Crazy');
insert into song_songwriter values (16, 5);
insert into track values (default, 'Let_s Go Crazy', 274, 6, 16);
insert into track_genre values (16, 1);
insert into track_genre values (16, 2);
insert into track_genre values (16, 8);
insert into song values (default, 'Darling Nikki');
insert into song_songwriter values (17, 5);
insert into track values (default, 'Darling Nikki', 244, 6, 17);
insert into track_genre values (17, 1);
insert into track_genre values (17, 2);
insert into track_genre values (17, 8);
insert into song values (default, 'Purple Rain');
insert into song_songwriter values (18, 5);
insert into track values (default, 'Purple Rain', 237, 6, 18);
insert into track_genre values (18, 1);
insert into track_genre values (18, 2);
insert into track_genre values (18, 8);

insert into artist values (default, 'Madonna');
insert into artist values (default, 'Justin Timberlake');
insert into artist values (default, 'Timbaland');
insert into songwriter values (default, 'Madonna');
insert into album values (default, 'Hard Candy', 2008);
insert into artist_album values (5, 7, TRUE);
insert into artist_album values (6, 7, FALSE);
insert into artist_album values (7, 7, FALSE);
insert into song values (default, '4 Minutes');
insert into song_songwriter values (19, 6);
insert into track values (default, '4 Minutes', 245, 7, 19);
insert into track_genre values (19, 2);
insert into song values (default, 'Heartbeat');
insert into song_songwriter values (20, 6);
insert into track values (default, 'Heartbeat', 243, 7, 20);
insert into track_genre values (20, 2);
insert into song values (default, 'Incredible');
insert into song_songwriter values (21, 6);
insert into track values (default, 'Incredible', 380, 7, 21);
insert into track_genre values (21, 2);

insert into artist values (default, 'Eminem');
insert into artist values (default, '50 Cent');
insert into artist values (default, 'Nate Dogg');
insert into artist values (default, 'Dr. Dre');
insert into songwriter values (default, 'Eminem');
insert into album values (default, 'Encore', 2004);
insert into artist_album values (8, 8, TRUE);
insert into artist_album values (9, 8, FALSE);
insert into artist_album values (10, 8, FALSE);
insert into artist_album values (11, 8, FALSE);
insert into song values (default, 'Mosh');
insert into song_songwriter values (22, 7);
insert into track values (default, 'Mosh', 318, 8, 22);
insert into track_genre values (22, 2);
insert into track_genre values (22, 3);
insert into song values (default, 'Never Enough');
insert into song_songwriter values (23, 7);
insert into track values (default, 'Never Enough', 160, 8, 23);
insert into track_genre values (23, 2);
insert into track_genre values (23, 3);
insert into song values (default, 'Encore');
insert into song_songwriter values (24, 7);
insert into track values (default, 'Encore', 313, 8, 24);
insert into track_genre values (24, 2);
insert into track_genre values (24, 3);

insert into artist values (default, 'Pink Floyd');
insert into songwriter values (default, 'Roger Waters');
insert into album values (default, 'Dark Side Of The Moon', 1973);
insert into artist_album values (12, 9, TRUE);
insert into song values (default, 'Time');
insert into song_songwriter values (25, 8);
insert into track values (default, 'Time', 414, 9, 25);
insert into track_genre values (25, 1);
insert into song values (default, 'Money');
insert into song_songwriter values (26, 8);
insert into track values (default, 'Money', 383, 9, 26);
insert into track_genre values (26, 1);
insert into song values (default, 'Eclipse');
insert into song_songwriter values (27, 8);
insert into track values (default, 'Eclipse', 130, 9, 27);
insert into track_genre values (27, 1);

insert into artist values (default, 'John Denver');
insert into songwriter values (default, 'John Denver');
insert into album values (default, 'Back Home Again', 1974);
insert into artist_album values (13, 10, TRUE);
insert into song values (default, 'Matthew');
insert into song_songwriter values (28, 9);
insert into track values (default, 'Matthew', 228, 10, 28);
insert into track_genre values (28, 4);
insert into song values (default, 'Eclipse');
insert into song_songwriter values (29, 9);
insert into track values (default, 'Eclipse', 225, 10, 29);
insert into track_genre values (29, 4);
insert into song values (default, 'On The Road');
insert into song_songwriter values (30, 9);
insert into track values (default, 'On The Road', 157, 10, 30);
insert into track_genre values (30, 4);

insert into artist values (default, 'Kraftwerk');
insert into songwriter values (default, 'Fritz Hilpert');
insert into album values (default, 'The Mix', 1991);
insert into artist_album values (14, 11, TRUE);
insert into song values (default, 'The Robots');
insert into song_songwriter values (31, 10);
insert into track values (default, 'The Robots', 539, 11, 31);
insert into track_genre values (31, 5);
insert into song values (default, 'Dentaku');
insert into song_songwriter values (32, 10);
insert into track values (default, 'Dentaku', 207, 11, 32);
insert into track_genre values (32, 5);
insert into song values (default, 'Abzug');
insert into song_songwriter values (33, 10);
insert into track values (default, 'Abzug', 138, 11, 33);
insert into track_genre values (33, 5);

insert into artist values (default, 'Green Day');
insert into songwriter values (default, 'Billy Joe Armstrong');
insert into album values (default, 'Dookie', 1994);
insert into artist_album values (15, 12, TRUE);
insert into song values (default, 'Burnout');
insert into song_songwriter values (34, 11);
insert into track values (default, 'Burnout', 128, 12, 34);
insert into track_genre values (34, 6);
insert into track_genre values (34, 2);
insert into song values (default, 'Chump');
insert into song_songwriter values (35, 11);
insert into track values (default, 'Chump', 174, 12, 35);
insert into track_genre values (35, 6);
insert into track_genre values (35, 2);
insert into song values (default, 'She');
insert into song_songwriter values (36, 11);
insert into track values (default, 'She', 134, 12, 36);
insert into track_genre values (36, 6);
insert into track_genre values (36, 2);

insert into artist values (default, 'Bob Dylan');
insert into songwriter values (default, 'Bob Dylan');
insert into album values (default, 'John Wesley Harding', 1967);
insert into artist_album values (16, 13, TRUE);
insert into song values (default, 'All Along The Watchtower');
insert into song_songwriter values (37, 12);
insert into track values (default, 'All Along The Watchtower', 151, 13, 37);
insert into track_genre values (37, 1);
insert into track_genre values (37, 7);

insert into artist values (default, 'Jimi Hendrix');
insert into album values (default, 'Electric Ladyland', 1968);
insert into artist_album values (17, 14, TRUE);
insert into track values (default, 'All Along The Watchtower', 241, 14, 37);
insert into track_genre values (38, 1);
