// Markdown to test came from: http://www.markitdown.net/markdown
var marked = require('marked');
var fs = require('fs');

var str = "# An exhibit of Markdown\nThis note demonstrates some of what [Markdown][1] is capable of doing.\n*Note: Feel free to play with this page. Unlike regular notes, this doesn't automatically save itself.*\n## Basic formatting\nParagraphs can be written like so. A paragraph is the basic block of Markdown. A paragraph is what text will turn into when there is no reason it should become anything else.\nParagraphs must be separated by a blank line. Basic formatting of *italics* and **bold** is supported. This *can be **nested** like* so.\n## Lists\n### Ordered list\n1. Item 1\n2. A second item\n3. Number 3\n4. Ⅳ\n*Note: the fourth item uses the Unicode character for [Roman numeral four][2].*\n### Unordered list\n* An item\n* Another item\n* Yet another item\n* And there's more...\n## Paragraph modifiers\n### Code block\n    Code blocks are very useful for developers and other people who look at code or other things that are written in plain text. As you can see, it uses a fixed-width font.\nYou can also make `inline code` to add code into other things.\n### Quote\n> Here is a quote. What this is should be self explanatory. Quotes are automatically indented when they are used.\n## Headings\nThere are six levels of headings. They correspond with the six levels of HTML headings. You've probably noticed them already in the page. Each level down uses one more hash character.\n### Headings *can* also contain **formatting**\n### They can even contain `inline code`\nOf course, demonstrating what headings look like messes up the structure of the page.\nI don't recommend using more than three or four levels of headings here, because, when you're smallest heading isn't too small, and you're largest heading isn't too big, and you want each size up to look noticeably larger and more important, there there are only so many sizes that you can use.\n## URLs\nURLs can be made in a handful of ways:\n* A named link to [MarkItDown][3]. The easiest way to do these is to select what you want to make a link and hit `Ctrl+L`.\n* Another named link to [MarkItDown](http://www.markitdown.net/)\n* Sometimes you just want a URL like <http://www.markitdown.net/>.\n## Horizontal rule\nA horizontal rule is a line that goes across the middle of the page.\n---\nIt's sometimes handy for breaking things up.\n## Images\nMarkdown can also contain images. I'll need to add something here sometime.\n## Finally\nThere's actually a lot more to Markdown than this. See the official [introduction][4] and [syntax][5] for more information. However, be aware that this is not using the official implementation, and this might work subtly differently in some of the little things.\n  [1]: http://daringfireball.net/projects/markdown/\n  [2]: http://www.fileformat.info/info/unicode/char/2163/index.htm=\n  [3]: http://www.markitdown.net/\n  [4]: http://daringfireball.net/projects/markdown/basics\n  [5]: http://daringfireball.net/projects/markdown/syntax";

var arr = str.split("\n");
var new_str = arr.reduce(function(a,b) {
  return a + marked(b);
},"");
fs.writeFile('marked-test.html', new_str, function(err) {
  if (err) throw err;
});
